### ISSUE TITLE
[BUG] Up and down arrow keys no longer work in message input field in Session Desktop 1.16.x

### ISSUE THREAD

**Issue by 2011** [session-foundation/session-desktop#1612]
### Code of conduct

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/session-foundation/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [x] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When composing a message, I frequently use to up and down arrow keys to go forward and back through the message. They no longer work (Linux AppImage).

### Expected Behavior

I expect that when I press the up arrow key that the cursor will move up one line, and when I press the down arrow key that the cursor will move down one line.

### Steps To Reproduce

1. Compose a message with multiple lines.
2. Attempt to use the up or down arrow keys to move the cursor.
3. Cursor does not move.

### Desktop Version

Using the latest version available at the time of filing this issue (1.16.10).

**Comment by pottsandpans** [comment]
Thanks for raising! This bug is fixed in 1.17.1.

**Comment by 2011** [comment]
@pottsandpans Still not working reliably in 1.17.1. If I (in the message box) paste a link at the beginning of the message, and then use the home key to go to the beginning of the link, then the down arrow key does not work (perhaps other actions demonstrate this, as well, but I can reproduce the problem every time using this sequence). I don't know if it matters, but I use the AppImage.

**Comment by 2011** [comment]
@pottsandpans Please reopen.
